[target.x86_64-pc-windows-msvc]
    # 使用 lld-link 取代 MSVC link.exe，避開 PDB LNK1318 問題
    linker = "rust-lld.exe"

[source.crates-io]
    # replace-with = 'cqu'

[source.tsinghua]
    registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[registries.tsinghua]
    index = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[source.cqu]
    registry = "sparse+https://mirrors.cqu.edu.cn/crates.io-index/"

[registries.cqu]
    index = "sparse+https://mirrors.cqu.edu.cn/crates.io-index/"

[build]
    rustc-wrapper = "sccache"

