"$schema" = 'https://starship.rs/config-schema.json'

format       = "$time$all"
right_format = "${env_var.yazi_level}$shlvl$cmd_duration$battery"

[character]
    success_symbol = "[â¯](bold green)"
    error_symbol   = "[! â¯](bold red)"

[battery]
    disabled = false
    [[battery.display]]
        threshold = 50

[shlvl]
    disabled = false
[git_metrics]
    disabled = false

[directory]
    truncation_length = 5
    truncation_symbol = ".../"

[time]
    disabled    = false
    time_format = "%R"

[env_var.yazi_level]
    description = "Indicate the shell was launched by `yazi`"
    variable    = "YAZI_LEVEL"
    # ğŸ¦†: U+1f986 Duck
    # Alternatively: "î• ": U+E795 <Private Use>
    symbol = "ğŸ¦†"
    format = '[ $symbol ]($style)'
